version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: mydb
      DB_HOST: db
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
